name       : haskell-filemanip
version    : 0.3.6.3
release    : 3
source     :
    - https://hackage.haskell.org/package/filemanip-0.3.6.3/filemanip-0.3.6.3.tar.gz : 8836da17baaaf02ca080c9990ece4e0b0c8d6a128f458f8b64fd07b225ca9846
license    : BSD-3-Clause
component  : programming.haskell
summary    : A Haskell library for working with files and directories. Includes code for pattern matching, finding files, modifying file contents, and more.
description: |
    A Haskell library for working with files and directories. Includes code for pattern matching, finding files, modifying file contents, and more.
builddeps  :
    - haskell-cabal-install
    - haskell-unix-compat-devel
rundeps    :
    - devel:
        - haskell-unix-compat-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
